# Generated by Django 4.2.16 on 2024-12-08 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminID', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('UserID', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Answer', models.CharField(max_length=255)),
                ('SubscribeIDs', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('E_ID', models.AutoField(primary_key=True, serialize=False)),
                ('E_Op', models.IntegerField()),
                ('E_Content', models.CharField(max_length=200)),
                ('E_State', models.CharField(max_length=20)),
                ('E_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('E_Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_Recipient', to='accounts.useraccount')),
                ('E_Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_Sender', to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Sex', models.BooleanField(default=0)),
                ('Tag', models.CharField(default='@,@,@', max_length=80)),
                ('Info', models.CharField(default='这个人很懒什么都没有写', max_length=500)),
                ('I_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Info', to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Image', models.ImageField(default='user_images/default.png', upload_to='user_images/')),
                ('M_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_CreateActivity', models.CharField(default='', max_length=1000)),
                ('A_JoinActivity', models.CharField(default='', max_length=1000)),
                ('A_WaiteActivity', models.CharField(default='', max_length=1000)),
                ('A_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='accounts.useraccount')),
            ],
        ),
    ]
