/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Chat': RouteRecordInfo<'/Chat', '/Chat', Record<never, never>, Record<never, never>>,
    '/ChatPersonal': RouteRecordInfo<'/ChatPersonal', '/ChatPersonal', Record<never, never>, Record<never, never>>,
    '/CreateActivity': RouteRecordInfo<'/CreateActivity', '/CreateActivity', Record<never, never>, Record<never, never>>,
    '/DetailActivity': RouteRecordInfo<'/DetailActivity', '/DetailActivity', Record<never, never>, Record<never, never>>,
    '/DetailActivityManager': RouteRecordInfo<'/DetailActivityManager', '/DetailActivityManager', Record<never, never>, Record<never, never>>,
    '/EditUserInfo': RouteRecordInfo<'/EditUserInfo', '/EditUserInfo', Record<never, never>, Record<never, never>>,
    '/FindPassword': RouteRecordInfo<'/FindPassword', '/FindPassword', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/LoginManager': RouteRecordInfo<'/LoginManager', '/LoginManager', Record<never, never>, Record<never, never>>,
    '/LoginUser': RouteRecordInfo<'/LoginUser', '/LoginUser', Record<never, never>, Record<never, never>>,
    '/Manager': RouteRecordInfo<'/Manager', '/Manager', Record<never, never>, Record<never, never>>,
    '/ManageTeam': RouteRecordInfo<'/ManageTeam', '/ManageTeam', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/Person': RouteRecordInfo<'/Person', '/Person', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/Welcome': RouteRecordInfo<'/Welcome', '/Welcome', Record<never, never>, Record<never, never>>,
  }
}
