# Generated by Django 4.2.16 on 2024-12-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplyID', models.IntegerField(primary_key=True, serialize=False, verbose_name='申请ID')),
                ('ActivityID', models.IntegerField(verbose_name='活动ID')),
                ('ApplicantID', models.IntegerField(verbose_name='申请人ID')),
                ('Status', models.BooleanField(verbose_name='状态')),
                ('Time', models.CharField(max_length=255, verbose_name='时间')),
            ],
            options={
                'verbose_name': '申请',
                'verbose_name_plural': '申请',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomID', models.CharField(max_length=255)),
                ('UserID', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('AvatarUrl', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('First', models.CharField(max_length=255)),
                ('Second', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendUserID', models.CharField(max_length=255)),
                ('ReceiveUserID', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('CreatorID', models.CharField(blank=True, max_length=255, null=True)),
                ('CampusID', models.CharField(max_length=255)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(max_length=255)),
                ('StartDate', models.DateTimeField(blank=True, null=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('NeedRealName', models.BooleanField(blank=True, default=False, null=True)),
                ('NumCurrent', models.IntegerField(blank=True, default=1, null=True)),
                ('NumLimit', models.IntegerField(blank=True, null=True)),
                ('ParticipantsID', models.CharField(blank=True, max_length=255, null=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.class')),
                ('RoomID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lists.chatmessage')),
            ],
        ),
    ]
